version: "3"
services:
  desktop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: linux-desktop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - SUBFOLDER=/
      - TITLE=Linux-Coder
    network_mode: service:tailscale
    restart: always

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: codespace-linux
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=tskey-auth-kVTTehhFJb11CNTRL-zRk9vK5EFxbC38ZoBhBbwb7dWpjCmyGvd
      - TS_STATEFUL=true
    restart: on-failure
    
