version: '3'
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 3389:3389
      - 8006:8006
    stop_grace_period: 2m
    environment:
      VERSION: "10"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
    volumes:
      - ./win_data:/storage
    restart: on-failure
    
