
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    environment:
      VERSION: "https://software-static.download.prss.microsoft.com/dbazure/88896407-ad00-4dc7-9759-3c549f05f747/22631.2428.231001-0608.23H2_NI_RELEASE_SVC_REFRESH_CLIENTENTERPRISEEVAL_OEMRET_X64FRE_EN-US.ISO"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      USER: "admin"
      PASS: "root123"
    network_mode: service:tailscale
    restart: on-failure

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: codespace-win10
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=tskey-auth-kVTTehhFJb11CNTRL-zRk9vK5EFxbC38ZoBhBbwb7dWpjCmyGvd
      - TS_STATEFUL=true
    restart: on-failure
